### ISSUE TITLE
Add antibiotic Azithromycin

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMHiDB#109]
Soon [microdilution](https://en.wikipedia.org/wiki/Broth_microdilution) will be used for internal purpose (not for resistence evaluating)

- [x] Values for Azithromycin can be added to isolates
- [x] Evaluation is done using CLSI M100 (2020) with susceptible ≤2 and resistent >2
- [x] Provided MHK steps should be `0,03/0,06/0,125/0,25/0,5/1/2/4/8/16`
- [x] Laboratory export includes values for Azithromycin 
- [x] Reports will not list values for Azithromycin

**Comment by markusrt** [comment]
@hclaus24 Some additional questions:

- Which MHK steps should be provided for Azithromycin/CLSI?
  e.g.
  <img width="181" alt="image" src="https://user-images.githubusercontent.com/299753/145282609-9cb97bb5-8f00-43d6-b265-892c1b7bdc17.png">
- Is assumption correct, that these values are not listed on reports?
- Should the value be included in laboratory export?
- Is it ok to add the new Antibiotic to the same section as EUCAST (E-Tests) or should there be a separate part for CLSI?
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/299753/145283152-076781ac-5100-4739-aae0-25bfed5212d9.png">

**Comment by hclaus24** [comment]
> @hclaus24 Some additional questions:
> 
>     * Which MHK steps should be provided for Azithromycin/CLSI?
>       e.g.
>       <img alt="image" width="181" src="https://user-images.githubusercontent.com/299753/145282609-9cb97bb5-8f00-43d6-b265-892c1b7bdc17.png">

**MHK steps: 0,03/0,06/0,125/0,25/0,5/1/2/4/8/16**
> 
>     * Is assumption correct, that these values are not listed on reports?
> 
>     * Should the value be included in laboratory export?

**values will not be listed in reports but should be included in laboratory exports**
> 
>     * Is it ok to add the new Antibiotic to the same section as EUCAST (E-Tests) 

**yes**

or should there be a separate part for CLSI?
>       <img alt="image" width="600" src="https://user-images.githubusercontent.com/299753/145283152-076781ac-5100-4739-aae0-25bfed5212d9.png">
