### ISSUE TITLE
Report generation for Meningococci

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMHiDB#12]
A report according the current template is created and filled with all required isolate, sender, and sending properties.

**Comment by markusrt** [comment]
`StemRules.json` is still following the legacy format hence an update to the multiline report is still missing. Same for `Untersuchungsbefund.docx`

**Comment by markusrt** [comment]
Additionally make sure all interpretation rules are implemented

**Comment by markusrt** [comment]
**Question**
Additional issues (via Email 05.02.2020)
- When PCR is inibitory then no rules match for native material
- For vital stems with no growth where serogroup is determined via molecular typing then no rule is matching once por and fet results are entered

**Comment by markusrt** [comment]
Heike:
Try to formulate the sentence:
"Die Serogruppen B und C-spezifischen csb- und csc-Gene wurden nicht nachgewiesen."
to somehow contain "inhibitorisch" or "negativ"

**Comment by markusrt** [comment]
Fixed: ~~When PCR is inibitory then no rules match for native material~~

**Comment by hclaus24** [comment]
ABC stands for any possible value of agglutination.

 

Viele Grüße

 

Heike

_________________________________

 

Heike Claus

Institut für Hygiene und Mikrobiologie

Universität Würzburg

Josef-Schneider-Str. 2 / E1

97080 Würzburg

Germany

 

Tel. ++49 (0)931 31 46936 oder 46906 

Fax ++49 (0)931 31 46445

e-mail hclaus@hygiene.uni-wuerzburg.de

 

Von: Markus Reinhardt [mailto:notifications@github.com] 
Gesendet: Freitag, 22. Mai 2020 19:02
An: markusrt/NRZMHiDB
Cc: hclaus24; Mention
Betreff: Re: [markusrt/NRZMHiDB] Report generation for Meningococci (#12)

 

@hclaus24 <https://github.com/hclaus24>  I am just double checking the rules:

 <https://user-images.githubusercontent.com/299753/82691364-14ea9c00-9c5e-11ea-8b2b-673b111c0700.png> Das Bild wurde vom Absender entfernt. image

What is ABC here referring to. Is it really only A, B, or C or any possible value of Agglutination despite n.d.?

https://github.com/markusrt/NRZMHiDB/blob/b23711797a0f5352a9de3ba9433ad14485fa2504/HaemophilusWeb/Models/Meningo/MeningoSerogroupAgg.cs#L8-L19

**Comment by markusrt** [comment]
@hclaus24 ok there are still some open questions:

Once again all rules mentioning "Serogruppen-PCR=ABC": With "any possible value" you mean `A, B, C, E, W, X, Y, Z, W/Y` excluding `Negative, Auto, Poly` correct?

Rule 15/16 should print
> Meldekategorie dieses Befundes: Neisseria meningitidis, Serogruppe ABC.
isn't `ABC` always negative in these cases?

**Comment by hclaus24** [comment]
You are right. It should read: Neisseria meningitidis, unbekapselt

 

Viele Grüße

 

Heike

_________________________________

 

Heike Claus

Institut für Hygiene und Mikrobiologie

Universität Würzburg

Josef-Schneider-Str. 2 / E1

97080 Würzburg

Germany

 

Tel. ++49 (0)931 31 46936 oder 46906 

Fax ++49 (0)931 31 46445

e-mail hclaus@hygiene.uni-wuerzburg.de

 

Von: Markus Reinhardt [mailto:notifications@github.com] 
Gesendet: Sonntag, 24. Mai 2020 15:24
An: markusrt/NRZMHiDB
Cc: hclaus24; Mention
Betreff: Re: [markusrt/NRZMHiDB] Report generation for Meningococci (#12)

 

@hclaus24 <https://github.com/hclaus24>  ok there are still some open questions:

Once again all rules mentioning "Serogruppen-PCR=ABC": With "any possible value" you mean A, B, C, E, W, X, Y, Z, W/Y excluding Negative, Auto, Poly correct?

Rule 15/16 should print

Meldekategorie dieses Befundes: Neisseria meningitidis, Serogruppe ABC.
isn't ABC always negative in these cases?

**Comment by hclaus24** [comment]
@markusrt 

Now I've up-dated several rules, hopefully correct:

- rules 30, 31 and 32
Serogenogruppe: nicht gruppierbar
Meldekategorie  ...Neisseria meningitidis, NG (keine Serogruppe bestimmbar).

- rules 15, 16, 19, 20, 23, 24
Meldekategorie ... Neisseria meningitidis, , cnl (capsule null locus).

- possible values for "Serogruppen-PCR=ABC" are  A, B, C, E, W, X, Y, Z, W/Y and cnl.

[Interpretationssatz Vorschrift_Nm_20200525.xlsx](https://github.com/markusrt/NRZMHiDB/files/4677071/Interpretationssatz.Vorschrift_Nm_20200525.xlsx)

**Comment by markusrt** [comment]
It looks strange if a report is empty:
![image](https://user-images.githubusercontent.com/299753/82864275-7e9bcc00-9f24-11ea-8fe4-ad98546b40d7.png)

In this case at least Identification should be shown and maybe a - on report text.

Example is data set 10130
