### ISSUE TITLE
RKI Export

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMHiDB#25]
Implement RKI export feature for Meningococci

**Comment by markusrt** [comment]
@hclaus24  For Hamophilus the RKI export is limited to a list of sampling locations (Blood, Liquor). Is it the same for Meningococci?

**Comment by hclaus24** [comment]
Hallo Markus,

 

meningococci are classified as invasive when they were sampled from Blut / Liquor / Petechien / Gelenkspunktat / Serum  (blood / CSF [cerebrospinal fluid] / petechiae / joint fluid / serum).

 

Viele Grüße

 

Heike

_________________________________

 

Heike Claus

Institut für Hygiene und Mikrobiologie

Universität Würzburg

Josef-Schneider-Str. 2 / E1

97080 Würzburg

Germany

 

Tel. ++49 (0)931 31 46936 oder 46906 

Fax ++49 (0)931 31 46445

e-mail hclaus@hygiene.uni-wuerzburg.de

 

Von: Markus Reinhardt [mailto:notifications@github.com] 
Gesendet: Samstag, 2. Mai 2020 12:01
An: markusrt/NRZMHiDB
Cc: hclaus24; Mention
Betreff: Re: [markusrt/NRZMHiDB] RKI Export (#25)

 

@hclaus24 <https://github.com/hclaus24>  For Hamophilus the RKI export is limited to a list of sampling locations (Blood, Liquor). Is it the same for Meningococci?

**Comment by markusrt** [comment]
@hclaus24  Ok get it. Invasive flag is already available. I.e. the export should only include invasive locations. Thanks 👍

**Comment by markusrt** [comment]
[Nm_RKI-Export_neu.xlsx](https://github.com/markusrt/NRZMHiDB/files/5885035/Nm_RKI-Export_neu.xlsx)
