### ISSUE TITLE
Server and application log retention

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMHiDB#28]
As part of TESSy it is required to comply with data privacy guidelines by RKI.

- Log files containing personal identifyable data should be deleted after 30 days

**Comment by markusrt** [comment]
@ulrichjosefvogel clarifies with RKI

**Comment by markusrt** [comment]
@ulrichjosefvogel 
I updated this issue according the new requirements

**Comment by ulrichjosefvogel** [comment]
Lieber Markus
Vielen Dank!

Mit freundlichen Grüßen
Ulrich Vogel

_____________________
Prof. Dr. Ulrich Vogel

Institut für Hygiene und Mikrobiologie, Universität Würzburg
Stabsstelle Krankenhaushygiene, Universitätsklinikum Würzburg

Gebäude E1
Josef-Schneider-Straße 2
97080 Würzburg

T 0931 31 46802, 0931 201 46802
M 0160 91911561


Am 02.08.2020 um 20:46 schrieb Markus Reinhardt <notifications@github.com>:

﻿

Closed #28<https://github.com/markusrt/NRZMHiDB/issues/28>.
