### ISSUE TITLE
patient number

### ISSUE THREAD

**Issue by thien-tri** [markusrt/NRZMHiDB#58]
please make the patient number visible to the user in both data bases (Hi and Nm). The Patient number should also appear in all exports. This will allow the user to better assess whether two submissions are duplicates or not.

**Comment by markusrt** [comment]
@thien-tri Where should the patient number be visible?

I.e. you mentioned the export, i.e. I would add it to the laboratory exports for Hi and Nm then.

Next possibility would be to add it to the Isolate details as well:
![image](https://user-images.githubusercontent.com/299753/89148564-80a08d80-d55a-11ea-9859-95fc856fabb2.png)

Any other places needed, i.e. list of all entries, report, ...?

**Comment by thien-tri** [comment]
good idea. It should appear in exports as well as in the isolate data as suggested.
thank you!

**Comment by markusrt** [comment]
@thien-tri added Patient Id to isolate edit view
![image](https://user-images.githubusercontent.com/299753/89208251-48ca3200-d5bc-11ea-8586-aa6f906cf529.png)

and to laboratory export
![image](https://user-images.githubusercontent.com/299753/89208313-67302d80-d5bc-11ea-8dfc-4b5d1c8181e5.png)

This is implemented for Hi and Nm database
