### ISSUE TITLE
Add antibiotics for Piperacillin/Tazobactam

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMHiDB#67]
- [x] Piperacillin/Tazobactam can be selected as antibiotic for measurements

**Comment by markusrt** [comment]
@thien-tri Can you provide breakpoints for the "Piperacillin/Tazobactam" combination?

**Comment by thien-tri** [comment]
The breakpoint ist 0.25 mg/L:
<=0.25 is S
> 0.25 is R
